# Generated by Django 4.1.7 on 2023-03-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='goods',
            name='update_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
