# Generated by Django 4.1.7 on 2023-03-04 06:48

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_to_child', to='app_menu.category', verbose_name='Категория'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent_category', 'slug')},
        ),
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
    ]
